"""Init migrate dan tambah alamat

Revision ID: bf199af2a3f5
Revises: 
Create Date: 2022-09-16 19:09:35.881808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf199af2a3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pengguna', sa.Column('alamat', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pengguna', 'alamat')
    # ### end Alembic commands ###
